name: Build Docker

on:
  workflow_dispatch:

jobs:
  docker:
    name: build-pg-${{ matrix.pg-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        pg-version:
          - "12"
          - "13"
#          - "14"
#          - "15"
#          - "16"
#          - "17"

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          version: "latest"

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Patch Docker
        working-directory: docker/
        run: |
          uv sync
          uv run patch_docker.py

      - name: Build and push
        id: docker-build
        uses: docker/bake-action@v5
        env:
          IMAGE_REPOSITORY: ghcr.io/${{ github.repository }}
        with:
          workdir: 'docker/'
          push: true
          targets: ${{ matrix.pg_version }}
          set: |
            *.platforms=linux/amd64,linux/arm64
            *.cache-to=type=gha
            *.cache-from=type=gha
            *.labels=${{ steps.meta.outputs.labels }}
            *.annotations=${{ steps.meta.outputs.annotations }}

      - name: Log output
        run: echo ${{ steps.docker-build.outputs.metadata }}
#      - name: Generate artifact attestation
#        uses: actions/attest-build-provenance@v1
#        with:
#          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
#          subject-digest: ${{ steps.push.outputs.digest }}
#          push-to-registry: true